### ISSUE TITLE
Roadmap v1.0.0

### ISSUE THREAD

**Issue by Nargonath** [booky/firefox-plugin#1]
Features list for the firefox plugin:

- [ ] Login

- [ ] Sign up

- [ ] Log out

- [ ] Sync manually your bookmarks upward

- [ ] Sync manually your bookmarks downward

- [ ] Merge manually your bookmarks upward

- [ ] Merge manually your bookmarks downward

- [ ] Handle automatically user interactions with their bookmarks (update/delete/insert)

- [ ] Delete my account and all data

**Comment by Nargonath** [comment]
Concerning data hosting, a better solution would be to make it part of user consideration rather centralizing all the data in one service which could get expansive if the user base grows. As such people would keep their hand on their data and the infrastructure cost would be on their side. Possible services to consider and offer connectors for them:
* Google Firebase
* CozyCloud
* Google Drive
* DropBox
* Glitch (?)
* Personal architecture with NodeJS server via Docker images etc.

If going in that direction, we might not need to handle login, logout and sign up feature because each user would be completely independent from each other.
